### ISSUE TITLE
 当第一个itemview高度大于屏幕时

### ISSUE THREAD

**Issue by AnMokoto** [sangmingming/Android-StickyNavLayout#1]

**Comment by w446108264** [comment]
因为你第一个itemview不是可scroll的布局，你需要将第一个itemview设为scrollview或其他可scroll的布局。
或https://github.com/w446108264/StickHeaderLayout

**Comment by AnMokoto** [comment]
不是针对scroll类型布局，是哪个head布局，超过屏幕高度时候会遮盖第二个和第三个可scoll的。

**Comment by AnMokoto** [comment]
已解决

**Comment by tzrgaga** [comment]
我遇到了一个问题，当listview item view超过一定高度 ，滑动到最后一个item的大部分时(最后一个item显示不全)就无法再滚动了，请教下，该怎么解决呢？
